# Generated by Django 4.2.16 on 2024-11-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_seller",
            field=models.BooleanField(default=False),
        ),
    ]
