# Generated by Django 4.2.16 on 2024-11-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_profile_is_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_seller",
        ),
    ]
