# Generated by Django 4.2.16 on 2024-11-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_profile_is_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/default_profile_pic.jpg",
                upload_to="profile_pics/",
            ),
        ),
    ]
