# Generated by Django 4.2.16 on 2024-12-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_user_token_created_at_user_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
