# Generated by Django 4.2.16 on 2024-12-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_user_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
